### ISSUE TITLE
The implementation can be found in keras_text_summarization/library/seq2seq.py

### ISSUE THREAD

**Issue by Mandrewoid** [chen0040/keras-text-summarization#1]
Dead link
https://github.com/chen0040/keras-text-summarization/blob/master/keras-text-summarization/blob/master/keras_text_summarization/library/seq2seq.py

**Comment by chen0040** [comment]
Hi @Mandrewoid thanks for the notification, i have rectified the problem, pls let me know if you came across such a problem again

**Comment by Mandrewoid** [comment]
Thanks for the good attitude :)
