### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by kim019** [chen0040/keras-text-summarization#5]
hi
seq2seq_predict.py 
one line summarization..
i want multiple line summarization...
Where should I fix it?
thanks.

**Comment by chen0040** [comment]
Can you given an example?

**Comment by kim019** [comment]
Hi 
I'm testing it using a demo example.
I do not know which part to fix, and I'm trying to change the variable.

seq2seq.py
self.xxxxx option

**Comment by mainakchain** [comment]
Hi @kim019 @chen0040 ! I haven't tried the model yet but can we get multiple line summarization using the same?

**Comment by kim019** [comment]
hi
i can't not speak english.. less.. very...

1 head line output..
i want 3~4 line summary.

Um..

Currently being modified and being tested.


Thanks.


2018년 6월 8일 (금) 15:06, Mainak Chain <notifications@github.com>님이 작성:
